### ISSUE TITLE
补充一个  dockercompose.yaml

### ISSUE THREAD

**Issue by bao3** [bitxeno/atvloadly#1]
补一个 Docker-compose 文件，也可以导入 Portainer 直接使用

```
# Build for Apple TV alterServer service
version: '3'
services:
  AppleTV:
    image: ghcr.io/bitxeno/atvloadly:latest
    container_name: AppleTV
    volumes:
      - /srv/docker/atvloadly:/data
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon:/var/run/avahi-daemon 
    ports:
      - 8080:80/tcp
    restart: unless-stopped
```
