### ISSUE TITLE
Apple TV HD with tvOS 18.4.1 not showing up for pairing (Synology NAS + Docker)

### ISSUE THREAD

**Issue by micer** [bitxeno/atvloadly#33]
I'm running Docker on my Synology NAS. I've created a container from atvloadly image. I'm using only `/volume1/docker/atvloadly:/data` volume.

For `dbus` and `avahi` I installed them in the same container, I had to run
```
chmod 777 /tmp && mkdir /run/dbus && apt update && apt install -y avahi-daemon avahi-utils
```
and then start both services via
```
dbus-daemon --system &
avahi-daemon --no-chroot &
```

Now, when I run `avahi-browser -a` from inside my Docker container, I can see my Apple TV (named "Living Room") in manual pairing mode:
```
root@atvloadly:/# avahi-browse -a | grep "Living\ Room"
+   eth0 IPv4 Living Room                                   _remotepairing-manual-pairing._tcp local
+   eth0 IPv4 70-35-60-63.1 Living Room                     _sleep-proxy._udp    local
+   eth0 IPv4 Living Room                                   _companion-link._tcp local
+   eth0 IPv4 AECE2CC8028C@Living Room                      AirTunes Remote Audio local
+   eth0 IPv4 Living Room                                   AirPlay Remote Video local
```

**It still doesn't show up on the atvloadly web page. What else could be wrong?**

<img width="1772" alt="Image" src="https://github.com/user-attachments/assets/b0835a91-89ec-42ce-813b-bb18afbd4869" />

**Comment by helloint** [comment]
I use docker compose without an issue.
```
version: '3.8'

services:
  atvloadly:
    image: bitxeno/atvloadly:latest
    container_name: atvloadly
    privileged: true
    restart: always
    ports:
      - "5533:80"
    volumes:
      - /volume1/docker/atvloadly/data:/data
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon:/var/run/avahi-daemon
```
But still could open the installed app, because of https://github.com/bitxeno/atvloadly/issues/32
